
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby

install: 'bundle install --retry=3'
script: 'ruby -r bundler/setup -S rake test:travis'

env:
  - 'RESTMORE=rest-more'
  - 'RESTMORE=rails3'

matrix:
  allow_failures:
    - rvm: 2.2
      env: 'RESTMORE=rails3'
