before_install: 'git submodule update --init'
script: 'ruby -r bundler/setup -S rake test:travis'

env:
  - 'RESTMORE=rest-more'
  - 'RESTMORE=rails3'

rvm:
  - 1.9
  - 2.0
  - 2.1
  - rbx-2
  - jruby
