
development: &default
  facebook:
    app_id: '123'
    secret: '456'
    canvas: 'can'
  macebook:
    app_id: 41829
    secret: <%= 'r41829'.reverse %>
    json_response: false
    lang: zh-tw
    auto_authorize_scope: 'publish_stream'

production:
  *default

test:
  *default
